### ISSUE TITLE
compilation terminated.

### ISSUE THREAD

**Issue by mergi-2674** [hahnlab/CAFE5#108]
Hi 
I was compiling CAFE5 in my linux machine and while i was on make step i received this error. 
/home/wbiw/miniconda3/bin/x86_64-conda-linux-gnu-c++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/likelihood_ratio.cpp -o obj/likelihood_ratio.o
/home/wbiw/miniconda3/bin/x86_64-conda-linux-gnu-c++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/matrix_cache.cpp -o obj/matrix_cache.o
src/matrix_cache.cpp:15:10: fatal error: mkl.h: No such file or directory
 #include "mkl.h"
          ^~~~~~~
compilation terminated.
make: *** [Makefile:35: obj/matrix_cache.o] Error 1

How can i fix it?

Thanks

**Comment by benfulton** [comment]
Can you install the Intel MKL math library? The installer is here: https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/onemkl.html

**Comment by ChaoShenzjs** [comment]
Hi was compiling CAFE5 in MAC and met an error as follows:
g++ -std=c++11 -I. -O3 -include config.h   -c src/cafexp.cpp -o obj/cafexp.o
src/cafexp.cpp:5:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
make: *** [obj/cafexp.o] Error 1
What should I do?
Thanks!
