### ISSUE TITLE
'make' fails.

### ISSUE THREAD

**Issue by hannahdevens** [hahnlab/CAFE5#111]
Hi, I am trying to install using the latest release, as recommended, and I am getting the following error on running make:
collect2: error: ld returned 1 exit status
make: *** [bin/cafe5] Error 1

I am on linux.

Thanks!

**Comment by hannahdevens** [comment]
Hi Ben, I tried installing on a different compute cluster and was able to make without issue, so I suspect whatever the issue was, it was tied to our older compute cluster (maybe our gcc version?). Thank you!

**Comment by benfulton** [comment]
Good to hear!
