### ISSUE TITLE
Compiling problem on MAC

### ISSUE THREAD

**Issue by ChaoShenzjs** [hahnlab/CAFE5#115]
Hi
How can I do with the following troubles when compiling CAFE5 on my MAC:
g++ -std=c++11 -O3  -o bin/cafe5 -I. obj/base_model.o obj/cafexp.o obj/clade.o obj/core.o obj/easylogging++.o obj/error_model.o obj/execute.o obj/gamma.o obj/gamma_core.o obj/gene_family.o obj/gene_family_reconstructor.o obj/io.o obj/lambda.o obj/likelihood_ratio.o obj/matrix_cache.o obj/optimizer.o obj/optimizer_scorer.o obj/poisson.o obj/probability.o obj/root_equilibrium_distribution.o obj/simulator.o obj/user_data.o obj/main.o -lm  
Undefined symbols for architecture arm64:
  "_omp_set_num_threads", referenced from:
      cafe5(int, char* const*) in cafexp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/cafe5] Error 1

Thanks!

**Comment by benfulton** [comment]
Make sure you have libomp installed. You can install it with Homebrew using

`brew install libomp`
