### ISSUE TITLE
compilation issue mac

### ISSUE THREAD

**Issue by piyalkarum** [hahnlab/CAFE5#118]
I linked omp.h as you explained in the installation instruction but now I get the following error

/usr/local/include/omp.h:308:45: error: '__malloc__' attribute takes no arguments
  __GOMP_NOTHROW __attribute__((__malloc__, __malloc__ (omp_free),

**Comment by benfulton** [comment]
That sounds like it might be an issue with the compiler. Are you using GCC? What version?

**Comment by piyalkarum** [comment]
I am using GCC and the version it shows on brew is this gcc: stable 12.2.0 (bottled), HEAD.

I had the error for 'omp.h' and I linked it as you explained in the instruction. This error was thrown when I tried to "make" it again after linking the omp.h.

**Comment by benfulton** [comment]
Any chance you could try gcc 10 instead? I wonder if there's a compatibility issue with the newer compiler.

**Comment by piyalkarum** [comment]
I tried with GCC 10 and I got the following error

/usr/local/Cellar/gcc@10/10.4.0/lib/gcc/10/gcc/x86_64-apple-darwin22/10.4.0/include-fixed/math.h:45:10: fatal error: sys/cdefs.h: No such file or directory
   45 | #include <sys/cdefs.h>

which then I linked with 
ln -sv /usr/local/Cellar/libunistring/1.1/include/unistring/cdefs.h /usr/local/include/

but I get the same error as above
