### ISSUE TITLE
How to compile cafexp

### ISSUE THREAD

**Issue by panosioannidis** [hahnlab/CAFE5#133]
In the tutorial, the `cafexp` program is used, but I couldn't find it in my `CAFE5/bin/` directory. However, I can find `cafexp.cpp` in the `CAFE5/src/` directory.

So, how can I compile it? Should I change something in the `Makefile`?

**Comment by benfulton** [comment]
No, use cafe5 instead (We changed the name at the last minute and apparently didn't catch all of the instances in the tutorial).

**Comment by panosioannidis** [comment]
Thanks Ben.
