### ISSUE TITLE
when I compile CAFE5 in Ubuntu , I get some error and don't konw how to solve

### ISSUE THREAD

**Issue by Wangsiyuan526** [hahnlab/CAFE5#156]
I uncompressed the CAFE5-5.1.0.tar.gz. ThenI followed RADEME's steps to compile CAFE5:
$ cd CAFE5/
$ ./configure
$ make
when i type make ,the process of compile got some error As shown in the following code：
/home/jianxins/anaconda3/bin/x86_64-conda-linux-gnu-c++ -std=c++11 -I. -O3 -include config.h -DDOCTEST_CONFIG_DISABLE -fopenmp  -c src/matrix_cache.cpp -o obj/matrix_cache.o
src/matrix_cache.cpp: In member function 'void matrix::multiply(const std::vector<double>&, int, int, int, int, double*) const':
src/matrix_cache.cpp:43:17: error: 'CblasRowMajor' was not declared in this scope
   43 |     cblas_dgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, m, n, k, alpha, sub, _size, &v[0], n, beta, result, n);
      |                 ^~~~~~~~~~~~~
src/matrix_cache.cpp:43:32: error: 'CblasNoTrans' was not declared in this scope
   43 |     cblas_dgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, m, n, k, alpha, sub, _size, &v[0], n, beta, result, n);
      |                                ^~~~~~~~~~~~
src/matrix_cache.cpp:43:5: error: 'cblas_dgemm' was not declared in this scope
   43 |     cblas_dgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, m, n, k, alpha, sub, _size, &v[0], n, beta, result, n);
      |     ^~~~~~~~~~~
make: *** [Makefile:35：obj/matrix_cache.o] error1

I'm a rookie about bioinformatics，and i can't find a right way to solve this error.
I wanna help,thank you

**Comment by benfulton** [comment]
This says the configure step found a math library, but the make step is unable to read it. What math library do you have on your system?

**Comment by zhujintaohome** [comment]
Hello, 
I have the same problem. I use `configure` command, and the math library is about this?

```shell
...
checking for library containing sgemm... -lmkl_intel_lp64
checking for library containing cblas_dgemm... no
checking for library containing vdExp... -lmkl_intel_lp64
configure: creating ./config.status
...
``` 
system: wsl, ubuntu
could you help me? i don't know how to solve it, thank you

> This says the configure step found a math library, but the make step is unable to read it. What math library do you have on your system?

**Comment by zhujintaohome** [comment]
@benfulton 

Hello, 
I have the same problem, I use `configure` command, and the math library might be this?
``` bash
...
checking for library containing sgemm... -lmkl_intel_lp64
checking for library containing cblas_dgemm... no
checking for library containing vdExp... -lmkl_intel_lp64
...
```

And I think it maybe due to the conda environment.
``` bash 
conda deactivate 
./configure
make  # then is ok
```

The problem is solved, but i also a fresh man, do not know why this happend. 
Best

> This says the configure step found a math library, but the make step is unable to read it. What math library do you have on your system?
