### ISSUE TITLE
Species is missing in output

### ISSUE THREAD

**Issue by chenym1** [hahnlab/CAFE5#170]
Hi,
In the output of cafe5, I found that the and maize are missing. What is the reason?

The Gamma_asr.tre is as following:
![image](https://github.com/hahnlab/CAFE5/assets/48475559/9fb24680-03a2-42ca-8997-dc4f9e43d654)

The Gamma_change.tab is as following:
![image](https://github.com/hahnlab/CAFE5/assets/48475559/976323a9-03f5-4bd9-98bd-4c258a36da87)

**Comment by benfulton** [comment]
Can you share your family and tree files?

**Comment by chenym1** [comment]
Thanks!
[gene_family_filter.txt](https://github.com/hahnlab/CAFE5/files/15064837/gene_family_filter.txt)
[Treefile.txt](https://github.com/hahnlab/CAFE5/files/15064843/Treefile.txt)

**Comment by benfulton** [comment]
I think this must be a different family file. This file has entries like Zeb, Cao, and Gao - the header of the family file has to match the species given in the tree file - rice, maize, sobi, etc.
