### ISSUE TITLE
CAFE 5, installation fail

### ISSUE THREAD

**Issue by pcampiteli** [hahnlab/CAFE5#190]
Greetings I'm trying to install the CAFE5 in a linux server. But the make command fails everytime 

I'm following the stadard procedure, even installed openBLAS via conda to compile, but the make fails and this error appears 

FROM THE ./configure command 
(CAFE) [h.paulocampiteli1@lagm CAFE5]$ ./configure
checking for icc... no
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for g++ option to support OpenMP... -fopenmp
checking for floor in -lm... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking mkl.h usability... no
checking mkl.h presence... no
checking for mkl.h... no
checking for library containing sgemm... no
checking for library containing cblas_dgemm... no
checking for library containing cblas_dgemm... -lopenblas
checking for library containing vdExp... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: config.h is unchanged
(CAFE) [h.paulocampiteli1@lagm CAFE5]$ ^C
(CAFE) [h.paulocampiteli1@lagm CAFE5]$ make
g++ -std=c++11 -O3 -fopenmp -o bin/cafe5 -I. obj/user_data.o obj/simulator.o obj/optimizer.o obj/likelihood_ratio.o obj/cafexp.o obj/probability.o obj/gene_family.o obj/newick_ape_loader.o obj/gamma.o obj/gamma_core.o obj/base_model.o obj/error_model.o obj/matrix_cache.o obj/core.o obj/lambda.o obj/io.o obj/root_equilibrium_distribution.o obj/report.o obj/clade.o obj/optimizer_scorer.o obj/poisson.o obj/execute.o obj/gene_family_reconstructor.o obj/easylogging++.o obj/main.o -lopenblas -lopenblas -lm
obj/matrix_cache.o: In function `matrix::multiply(std::vector<double, std::allocator<double> > const&, int, int, int, int, double*) const':
matrix_cache.cpp:(.text+0x37e): undefined reference to `cblas_dgemm(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, double, double const*, int, double const*, int, double, double*, int)'
collect2: error: ld returned 1 exit status
make: *** [bin/cafe5] Error 1
(CAFE) [h.paulocampiteli1@lagm CAFE5]$ export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
(CAFE) [h.paulocampiteli1@lagm CAFE5]$ make
g++ -std=c++11 -O3 -fopenmp -o bin/cafe5 -I. obj/user_data.o obj/simulator.o obj/optimizer.o obj/likelihood_ratio.o obj/cafexp.o obj/probability.o obj/gene_family.o obj/newick_ape_loader.o obj/gamma.o obj/gamma_core.o obj/base_model.o obj/error_model.o obj/matrix_cache.o obj/core.o obj/lambda.o obj/io.o obj/root_equilibrium_distribution.o obj/report.o obj/clade.o obj/optimizer_scorer.o obj/poisson.o obj/execute.o obj/gene_family_reconstructor.o obj/easylogging++.o obj/main.o -lopenblas -lopenblas -lm
obj/matrix_cache.o: In function `matrix::multiply(std::vector<double, std::allocator<double> > const&, int, int, int, int, double*) const':
matrix_cache.cpp:(.text+0x37e): undefined reference to `cblas_dgemm(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, double, double const*, int, double const*, int, double, double*, int)'
collect2: error: ld returned 1 exit status
make: *** [bin/cafe5] Error 1

My linux knowledge is limited so I'm can even say what is the exactly issue, hope someone can understand and help me. 

Thanks in advance

**Comment by benfulton** [comment]
It's not finding your OpenBLAS header for some reason. If you look in the file `config.h`, do you see the lines
```
#define HAVE_BLAS 1
#define HAVE_OPENBLAS 1
```

in it? If not, try adding them and run Make again.
