### ISSUE TITLE
There are only three columns in Base_family_results.txt

### ISSUE THREAD

**Issue by Edison2021** [hahnlab/CAFE5#31]
Hi Ben
In my base_family_results.txt, there are only three columns showing #FamilyID,	pvalue and Significant at 0.05. Other columns such as  ’c’ (constant), ’i’ (increasing), or ’d’ (decreasing) at nodes are missing. 

My command is cafexp -i gene_families.txt -t tree.txt. 

Any suggestions are appreciated! 

Edison

**Comment by Tong-Chen** [comment]
As shown by the code, only three-column result is supported now.

```
void reconstruction::print_increases_decreases_by_family(std::ostream& ost, const cladevector& order, familyvector& gene_families, const std::vector<double>& pvalues, double test_pvalue) {
    if (gene_families.size() != pvalues.size())
    {
        throw std::runtime_error("No pvalues found for family");
    }
    if (gene_families.empty())
    {
        ost << "No increases or decreases recorded\n";
        return;
    }

    ost << "#FamilyID\tpvalue\tSignificant at " << test_pvalue << "\n";

    for (size_t i = 0; i < gene_families.size(); ++i) {
        ost << gene_families[i].id() << '\t' << pvalues[i] << '\t';
        ost << (pvalues[i] < test_pvalue ? 'y' : 'n');
        ost << endl;
    }
}
```

**Comment by benfulton** [comment]
Yes, the increases and decreases were dropped, but can be calculated from some of the other output files. Did you find the c-i-d columns particularly helpful?

**Comment by Edison2021** [comment]
Hi Ben
I think these c-i-d columns are helpful. Could you please add them back?

Edison
