### ISSUE TITLE
p value calculation

### ISSUE THREAD

**Issue by madhubioinfo** [hahnlab/CAFE5#33]
base_family_results.txt only contains P value , rest of the columns are not present. How is the p value calculated for this? and does p value is calculated is calculated fro individual gene families ? base_family_likelihoods.txt results file also contains only two tab values with family and yes or no values, it doesn't have the likelihood values.

**Comment by benfulton** [comment]
P-value is calculated per family. The procedure is as follows:

1. For every possible root family size, randomly generate 1000 families based on the lambda
2. Compute the probability of each family generated, sort the results smallest to largest. The result is the
   conditional distribution.
3. Compute the probability of each of the user's families and calculate the pvalue from this likelihood and the 
   conditional distribution
