### ISSUE TITLE
Tutorial 2.3.1

### ISSUE THREAD

**Issue by wangxuann1995** [hahnlab/CAFE5#34]
Hi,
    I'm using OrthoFinder as the input of your tutorial in the CAFExp/doc. When I translate the tree to ultrametric tree and run python prep_r8s.py -i maximum_likelihood_tree.txt -o r8s_ctl_file.txt -s 35157236 -p 'human,cat' -c '94'. I wonder what -s(the number of sites in the alignment used to estimate the species tree) means, is it means "the number of columns in the alignment"?

Thanks in advance.
Wangxuan

**Comment by ZexinTong** [comment]
I have the same questions. Do you know how to get the correct number?

**Comment by benfulton** [comment]
The -s parameter is passed directly to r8s as its nsites parameter. According to the r8s manual,

> The nsites option indicates how many sites are in the sequences that were used to
> estimate the branch lengths in PAUP or some other program. Take care to insure this
> number is correct in cases in which sites have been excluded in the calculations of branch
> lengths (e.g., by excluding third positions in PAUP and then saving branch lengths). The
> program does not recognize exclusion sets or other PAUP commands that might have
> been used in getting the branch lengths.
