### ISSUE TITLE
Error "was not found in gene family"

### ISSUE THREAD

**Issue by pnatsi** [hahnlab/CAFE5#36]
Hello,

When I attempted to run the mammals example, I got the following error:

Command line: cafexp -i mammal_gene_families.txt -t mammal_tree.txt 
marmoset was not found in gene family ORTHOMCL1

The same error I got when I tried to use my own data. Any ideas what might be wrong?

Paschalis

**Comment by xylebori** [comment]
not sure why this occurred, seems to be running fine now, our earlier beta release may have had an issue with one of the example files having not been updated to match the example tree.
