### ISSUE TITLE
How can I know the family ID of the expansion and contraction familys in each species

### ISSUE THREAD

**Issue by wuxiaopei0509** [hahnlab/CAFE5#39]
Dear developer
I successfully run the program and get the results ,I get the number of expansion and contraction families in each node ,how could I know the family ID of each node?
Tnank a lot!

**Comment by zzzqiii** [comment]
I have the same question. Have you solved it?
Thanks a lot.

**Comment by Bioinformatics-rookie** [comment]
you can run  " cat Gamma_change.tab |cut -f1,15|grep "+[1-9]" >sample.expanded " to get the extended family of the species (or node) represented in column 15
run " cat Gamma_change.tab |cut -f1,15|grep "-" >sample.contracted " to get the contracted family of the species (or node) represented in column 15

**Comment by zuodabin** [comment]
Thank you for your answer, but my result is the result of CAFE4. How should I extract the gene ID of expansion and contraction?
