### ISSUE TITLE
error model estimation, output different than expected

### ISSUE THREAD

**Issue by Thijmen18** [hahnlab/CAFE5#42]
Dear all,

I'm new to CAFE, so apologies in advance if my question is rather basic.

I'm following the examples from the cafexp v5 github page using my own data. I have run the error model estimation and the run ended with:

Completed 36 iterations
Time: 0H 1M 11S
Best matches are: 0.0036202769661455,0.062594243085368
Final -lnL: 10467.871417275
104 values were attempted (0% rejected)

Inferring processes for Base model
Score (-lnL): 10467.871417275
Computing pvalues...done!
Starting reconstruction processes for Base model
Done!

The file that I expected describing the best error model "Base_error_model.txt" gives me:

maxcnt: 120
cntdiff: -1 0 1
0 0 0.937406 0.0625942
1 0.0625942 0.874812 0.0625942

There are no different files written mentioning error models. Am I interpreting this wrongly? I expected a file containing the most optimal error model (e.g. as described in the manual of version 4: "cafe_errormodel_0.10908203125.txt", that I could implement in the analyses.

Any help is appreciated.

**Comment by benfulton** [comment]
The Base_error_model.txt file is acceptable as an error model file. In CAFE 5, missing rows are assumed to be identical to the next smallest specified row, so in this case, all family sizes > 1 are assumed to be modeled as

0.0625942 0.874812 0.0625942
