### ISSUE TITLE
Support for Root nodes of Non-zero length

### ISSUE THREAD

**Issue by josiahseaman** [hahnlab/CAFE5#43]
Hi Ben,
I'm a big fan of CAFE. I have a PhD thesis chapter that includes a simulation which starts before the first speciation event. Can CAFE simulate changes along a single branch at the root for 24 million years before species begin branching out?  I have a WGD which determines my known state: 1 gene per "family" at the beginning of the species tree, then there's a 24 million year period before there's any speciation. I don't want to add in a dummy species just to support that duration because I end up with an extra column in all my output data.

I'd like to specify a root node at the end of my newick format like this:
`tree ((((((((((FRAX30:2.0,FRAX32:2.0):1.0,FRAX28:3.0):2.0,FRAX12:5.0):4.0,(FRAX07:8.0,FRAX29:8.0):1.0):4.0,FRAX08:13.0):1.0,(((((FRAX01:2.0,FRAX16:2.0):4.0,FRAX15:6.0):2.0,FRAX00:8.0):2.0,(FRAX06:9.0,FRAX23:9.0):1.0):3.0,FRAX25:13.0):1.0):3.0,FRAX21:17.0):2.0,(((FRAX19:8.0,FRAX20:8.0):2.0,((FRAX11:5.0,FRAX27:5.0):4.0,FRAX04:9.0):1.0):1.0,(((((FRAX03:1.0,FRAX09:1.0):1.0,FRAX13:2.0):2.0,(FRAX26:2.0,FRAX14:2.0):2.0):3.0,FRAX05:7.0):2.0,FRAX33:9.0):2.0):8.0):15.0,FRAX31:34.0):2.0,Oeuropaea:36.0):24.0;`

What's your recommendation?

**Comment by benfulton** [comment]
How about adding a fake outgroup that branched off 24 million years above the root? Set the distribution sizes at this new root to all be 1.

**Comment by josiahseaman** [comment]
This is what I ended up trying, but I got concerning results that made me think that the program is introducing rate artifacts somehow. The branch with the fake group is isolated into it's own evolutionary rate in the tree. I just added an extra column to my gene family counts and filled it with ones. But the new results with extra time has even less loss events in the interior of the species tree where they would be shared by the majority of species. Instead, almost all loss events are pushed to the tips, where they're shared by only a couple of the 27 species at a time. 

The additional fake Branch changed This:
![image](https://user-images.githubusercontent.com/2256148/98843924-d661bd00-2408-11eb-83d4-9cbe09d290d2.png)

To this:

![graphed_changes](https://user-images.githubusercontent.com/2256148/98843441-386df280-2408-11eb-83b5-11753468bbb9.png)

The first is much more biologically plausible than the second. So I concluded that something about the long branch with no changes is introducing unintended behavior. Getting surprising results is fine. Getting surprising results when introducing synthetic data to get the program to do something unintended seems like shaky ground to me. I would be forever in your debt if you could explain why this happened. It's pretty crucial to my research.

**Comment by xylebori** [comment]
Hi Josiah,

Can you paste the tree in that you used?

**Comment by josiahseaman** [comment]
Here's the cafe run script with some comments. Note that rootdist was ultimately not used. 2020_Feb08_homeolog_filtered_empty_WGD.txt contains a column called "empty" which contains all 1's.

```
load -i 2020_Feb08_homeolog_filtered_empty_WGD.txt -t 8 -l static_empty/two_rate_static_empty_0.1_error.log
tree (((((((((((FRAX30:2.0,FRAX32:2.0):1.0,FRAX28:3.0):2.0,FRAX12:5.0):4.0,(FRAX07:8.0,FRAX29:8.0):1.0):4.0,FRAX08:13.0):1.0,(((((FRAX01:2.0,FRAX16:2.0):4.0,FRAX15:6.0):2.0,FRAX00:8.0):2.0,(FRAX06:9.0,FRAX23:9.0):1.0):3.0,FRAX25:13.0):1.0):3.0,FRAX21:17.0):2.0,(((FRAX19:8.0,FRAX20:8.0):2.0,((FRAX11:5.0,FRAX27:5.0):4.0,FRAX04:9.0):1.0):1.0,(((((FRAX03:1.0,FRAX09:1.0):1.0,FRAX13:2.0):2.0,(FRAX26:2.0,FRAX14:2.0):2.0):3.0,FRAX05:7.0):2.0,FRAX33:9.0):2.0):8.0):15.0,FRAX31:34.0):2.0,Oeuropea:36.0):24.0,empty:60.0)
#rootdist -i single_copy_root.txt # caused segmentation errors
errormodel -model cafe_errormodel_0.1.txt -all
lambdamu -s -t (((((((((((1,1)1,1)1,1)1,(1,1)1)1,1)1,(((((1,1)1,1)1,1)1,(1,1)1)1,1)1)1,1)1,(((1,1)1,((1,1)1,1)1)1,(((((1,1)1,1)1,(1,1)1)1,1)1,1)1)1)1,1)1,1)1,2)
report static_empty/two_rate_static_empty
#export REPORT_SCRIPT=/data/SBCS-BuggsLab/Josiah/DNA_Duplications/CAFE-4.1/data/cafe_tutorial/python_scripts/cafetutorial_report_analysis.py
#python $REPORT_SCRIPT -i static_empty/two_rate_static_empty.cafe -o static_empty/Feb008_homeologs_static_empty_analysis
```

**Comment by xylebori** [comment]
Hi Josiah, it isn't immediately clear how one could accomplish what you are trying to do, mostly because the state of the root node is determined by the observed states at the tips.  Consider the scenario you have constructed in the figure below: 
![image](https://user-images.githubusercontent.com/8893005/98861659-a8de3900-2433-11eb-8e30-fb90e5edbd0b.png)

**Comment by josiahseaman** [comment]
Hi Dan,
That's a fair point about the root distribution. My question was more concerned though with why having a longer time period using "empty" group resulted in less change.  Specifically I'll highlight that one central node in the first result "+1 -1207" over 15 million years changes to "+113 -232" in the second result set. Meanwhile the new root branch is "+313 -0" or literally zero losses.  This looked strange to me and I couldn't explain it.

**Comment by xylebori** [comment]
Most likely because you aren't filtering families using the "-filter" flag, this means there are a bunch of families that get filtered in the first analysis, however when you add the empty taxon with all 1's this means a bunch of new families are analyzed because they are no longer being reconstructed with a zero value at the root.

**Comment by josiahseaman** [comment]
That does sound like a plausible explanation. Thank you!
