### ISSUE TITLE
installing error

### ISSUE THREAD

**Issue by yzhzu** [hahnlab/CAFE5#44]
today, I want to install CAFE 5.0 and got the error as following: 
./configure
checking for icc... no
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for g++ option to support OpenMP... -fopenmp
checking for floor in -lm... yes
checking for library containing sgemm... -lmkl_intel_lp64
checking for library containing cblas_dgemm... no
checking for library containing vdExp... -lmkl_intel_lp64
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
$ make
g++ -std=c++11 -O3 -fopenmp -o bin/cafexp -I. obj/user_data.o obj/simulator.o obj/optimizer.o obj/cafexp.o obj/probability.o obj/gene_family.o obj/gamma.o obj/matrix_cache.o obj/base_model.o obj/error_model.o obj/io.o obj/core.o obj/lambda.o obj/root_equilibrium_distribution.o obj/gamma_core.o obj/clade.o obj/optimizer_scorer.o obj/poisson.o obj/root_distribution.o obj/execute.o obj/gene_family_reconstructor.o obj/main.o -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_intel_lp64 -lm  
obj/clade.o: In function `parse_newick(std::string, bool)':
clade.cpp:(.text+0x451a): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::basic_regex<char, std::regex_traits<char> > const&, std::bitset<11ul>)'
clade.cpp:(.text+0x4527): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator()'
clade.cpp:(.text+0x4589): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator!=(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
clade.cpp:(.text+0x459e): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
clade.cpp:(.text+0x46f8): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator++(int)'
clade.cpp:(.text+0x4741): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
clade.cpp:(.text+0x48c9): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
clade.cpp:(.text+0x4ab1): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
clade.cpp:(.text+0x4b2a): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
clade.cpp:(.text+0x4bb6): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
obj/clade.o:clade.cpp:(.text+0x4d39): more undefined references to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()' follow
collect2: error: ld returned 1 exit status
make: *** [Makefile:32: bin/cafexp] Error 1
gcc -v
gcc version 5.2.0 (GCC) 
 can someone help me deal with the error? thank you very much.
                                                                                    yzhzhu

**Comment by benfulton** [comment]
If that is the exact sequence of commands you ran, you have leftover objects from a previous attempt. Try running

$ make clean

and then

$ make

**Comment by yzhzu** [comment]
Dear benfulton:
        thank you very much for your quick reply. when I follow your suggestion and the anothor error occurs as following:
make clean
make
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/user_data.cpp -o obj/user_data.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/simulator.cpp -o obj/simulator.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/optimizer.cpp -o obj/optimizer.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/cafexp.cpp -o obj/cafexp.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/probability.cpp -o obj/probability.o
src/probability.cpp:11:17: fatal error: mkl.h: No such file or directory
 #include "mkl.h"
                 ^
compilation terminated.
make: *** [Makefile:35: obj/probability.o] Error 1

**Comment by benfulton** [comment]
The Configure has found Intel's Math Kernel Library on your system, but for some reason it doesn't seem to be available to your compiler. Modify config.h and comment out the line

#define HAVE_VECTOR_EXP 1

Note that CAFE will run faster if the MKL is available.

**Comment by yzhzu** [comment]
Dear benfulton:
       thank you very much for your help. I have commented out the line: /* #define HAVE_VECTOR_EXP 1. 
       anothor error occurs as following:
make
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/user_data.cpp -o obj/user_data.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/simulator.cpp -o obj/simulator.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/optimizer.cpp -o obj/optimizer.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/cafexp.cpp -o obj/cafexp.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/probability.cpp -o obj/probability.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/gene_family.cpp -o obj/gene_family.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/gamma.cpp -o obj/gamma.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/matrix_cache.cpp -o obj/matrix_cache.o
src/matrix_cache.cpp:14:17: fatal error: mkl.h: No such file or directory
 #include "mkl.h"
                 ^
compilation terminated.
make: *** [Makefile:35: obj/matrix_cache.o] Error 1

       Do I  comment out the other line? 
       thanks
                                                         yzhzhu

**Comment by benfulton** [comment]
No, you will need to modify config.h again, and this time comment out 

#define HAVE_BLAS 1

**Comment by xylebori** [comment]
Hello yzhzu,

you can also try finding the mkl.h header file and providing it to the compiler.   You can do this by linking it to a directory in which the compiler looks for header files.  try this to get the directories in which the compiler is looking 

g++ -E -Wp,-v -xc++ /dev/null

try this to find mkl.h 

find / -name mkl.h 

link them 

ln -sv path/to/mkl.h   path/to/a/directory/searched/by/compiler
