### ISSUE TITLE
libstdc++.so.6 not found

### ISSUE THREAD

**Issue by ypchan** [hahnlab/CAFE5#45]
Hello, 
I compiled cafe5 successfully, but when I invoke it, error like the below. Could you give some some suggestions?
Thank you!

$./cafe5
`
./cafe5: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ./cafe5)
./cafe5: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./cafe5)
./cafe5: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by ./cafe5)
./cafe5: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by ./cafe5)
./cafe5: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./cafe5)
./cafe5: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./cafe5)
./cafe5: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./cafe5)
./cafe5: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./cafe5)
`

**Comment by benfulton** [comment]
That looks like a mess. The simplest thing to try is running 

$ make clean
$ make

to see if there are some artifacts left over from previous attempts. Otherwise I suspect your local system administrator would be more helpful. Is this a supercomputer? Which one?

**Comment by ypchan** [comment]
@benfulton 

Yes, I installed it in a computer cluster, and I have not root access. I solve it by change it's LD_LIBRARY_PATH.
Here is the solution, I hope it will help other people that have the same error.

# First
I checked the root directory check whether another newer version of libstdc++.so.6 was installed on the computer cluster. 
`$ find / -name "libstdc++.so.6"`

and I find another version, it seems to work.
/share/software/gcc-8.3.0/lib64/libstdc++.so.6

# Second
I created a symbolic link into the cafe5 bin directory
`ln -s /share/software/gcc-8.3.0/lib64/libstdc++.so.6 /data/user122/biosoft/CAFExp/bin/`

# Third
I created a intermediate file to change the LD_LIBRARY_PATH and reset it when cafe5 done.
```
mv cafe5 cafe5.ori
vi cafe5
```
write the following code into cafe5
```
#!/usr/bin/env bash
LD_LIBRARY_PATH_ORI=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/data/user122/biosoft/CAFExp/bin:$LD_LIBRARY_PATH
/data/user122/biosoft/CAFExp/bin/cafe5.ori $@
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH_ORI
```
# Last
`chmod 755 cafe5`
It seems to work well.
`./cafe5`


Usage: cafe5 [options]

CAFE is a software that provides a statistical foundation for evolutionary inferences about changes in gene family size.
 The program employs a birth and death process to model gene gain and loss across a user-specified phylogenetic tree,
 thus accounting for the species phylogenetic history. The distribution of family sizes generated under this model can
 provide a basis for assessing the significance of the observed family size differences among taxa.

OPTIONS:
  Required Options:
   --infile, -i                 Path to tab delimited gene families file to be analyzed - Required for estimation.
   --tree, -t                   Path to file containing newick formatted tree - Required for estimation.

  Common Options:
   --help, -h                   This help menu.
   --cores, -c                  Number of processing cores to use, requires an integer argument. Default=All available cores.
   --error_model, -e            Run with no file name to estimate the global error model file. This file can be provided
                                    in subsequent runs by providing the path to the Error model file with no spaces (e.g. -eBase_error_model.txt).
   --log_config, -L             Turn on logging, provide name of the configuration file for logging (see example log.config file).
   --n_gamma_cats, -k           Number of gamma rate categories to use. If specified, the Gamma model will be used to run
                                    calculations, otherwise the Base model will be used.
   --output_prefix, -o          Output directory - Name of directory automatically created for output. Default=results.
   --lambda_tree, -y            Path to lambda tree, for use with multiple lambdas.
   --fixed_alpha, -a            Alpha value of the discrete gamma distribution to use in category calculations. If not
                                    specified, the alpha parameter will be estimated by maximum likelihood.
   --fixed_lambda, -l           Value (between 0 and 1) for a single user provided lambda value, otherwise lambda is estimated.
   --fixed_multiple_lambdas, -m Multiple lambda values, comma separated.
   --poisson, -p                Use a Poisson distribution for the root frequency distribution. Without specifying this, a
                                    normal distribution will be used. A value can be specified -p10 (no space) or --poisson = 10,
                                    otherwise the distribution will be estimated from the gene families.
   --simulate, -s               Simulate families. Optionally provide the number of simulations to generate (-s100 no space, or --simulate = 100)
   --rootdist, -f               Path to root distribution file for simulating datasets.

  Less Common Options:
   --lambda_per_family, -b      Estimate lambda by family (for testing purposes only).
   --chisquare_compare, -r      Chi square compare.
   --pvalue, -P                 P-value to use for determining significance of family size change, Default=0.05.
   --zero_root, -z              Include gene families that don't exist at the root, not recommended.
   --Expansion, -E              Expansion parameter for Nelder-Mead optimizer, Default=2.
   --Iterations, -I             Maximum number of iterations that will be performed in
                                    lambda search. Default=300 (increase this number if likelihood is still improving when limit is hit).
   --Reflection, -R             Reflection parameter for Nelder-Mead optimizer, Default=1.

**For your timely reply expressed his gratitude at the same time express our admiration for your work!**
