### ISSUE TITLE
CAFE5 installation issue

### ISSUE THREAD

**Issue by shelbyLanda** [hahnlab/CAFE5#46]
Hello,

I am attempting to install CAFE5 and seem to be having issues with the make step of installation. 

I am not getting any error messages but make quits without creating the release folder or renaming the folder to CAFE5. This is the final output that I receive: 

```
g++ -std=c++11 -I. -O3 -include config.h -fopenmp  -c src/user_data.cpp -o obj/user_data.o
g++ -std=c++11 -I. -O3 -include config.h -fopenmp -c main.cpp -o obj/main.o
g++ -std=c++11 -O3 -fopenmp -o bin/cafexp -I. obj/base_model.o obj/cafexp.o obj/clade.o obj/core.o obj/error_model.o obj/execute.o obj/gamma_core.o obj/gamma.o obj/gene_family.o obj/gene_family_reconstructor.o obj/io.o obj/lambda.o obj/matrix_cache.o obj/optimizer.o obj/optimizer_scorer.o obj/poisson.o obj/probability.o obj/root_distribution.o obj/root_equilibrium_distribution.o obj/simulator.o obj/user_data.o obj/main.o -lm 
```

Am I missing a step?

Thanks,
~Shelby

**Comment by benfulton** [comment]
The final binary that is created will be in the bin folder, and named cafexp (in the beta) and cafe5 (in the release, coming Real Soon Now). If there was no error, you should have a bin/cafexp executable. No renaming of any folders occurs.

**Comment by shelbyLanda** [comment]
Ohh, okay. Great. So I can just add CAFE/bin to my file path and be good to go?

**Comment by benfulton** [comment]
Yes, should be.
