### ISSUE TITLE
was not found in gene family 

### ISSUE THREAD

**Issue by sajjadasaf** [hahnlab/CAFE5#47]
Hello,
I am trying to run cafe on my own data but it shows the following error.
I have tried old as well as new version but got same results.
Could you kindly help me to find out what is going wrong here?
I have attached files here.
[Family_gene.txt](https://github.com/hahnlab/CAFE5/files/5558479/Family_gene.txt)
[SpeciesTree_rooted.txt](https://github.com/hahnlab/CAFE5/files/5558482/SpeciesTree_rooted.txt)

**Comment by benfulton** [comment]
Your family file is encoded in UTF-16, while your tree is ASCII. 

$ file Family_gene.txt
Family_gene.txt: Little-endian UTF-16 Unicode text, with very long lines, with CRLF line terminators

You can fix it by running

$ iconv -f UTF16 -t ASCII Family_gene.txt -o Family_gene_ascii.txt

But you still have various file inconsistencies to fix after that.

**Comment by sajjadasaf** [comment]
Thank you for your reply.
It mean these two files generated by orthofinder can not be use in cafe ? Or is there any other way to convert both files to make it usable. Could you kindly point out few inconsistencies in this file to help me to remove it.
Thanks again for your help.

**Comment by benfulton** [comment]
It's mostly spaces in your species names. For example, your family file has "Cochliobolus miyabeanus ATCC 44560" as a species - you might try replacing the spaces with underscores. I also see you have "Cochliobolus victoriae FI3" and "Bipolaris_victoriae_fi3_gca_000527765", so you might make the capitalization more consistent.

**Comment by sajjadasaf** [comment]
Thank you for help. I will change it accordingly.

**Comment by sajjadasaf** [comment]
Hello,
I changed the family file and converted it to ascii but still the same problem.

Error:
Command line: cafe5 -i genefamily.txt -t tree3_ultrametric.txt 
sajjad was not found in gene family 





Could you kindly check it that where i am doing mistake.
[genefamily.txt](https://github.com/hahnlab/CAFE5/files/5873225/genefamily.txt)
[tree3_ultrametric.txt](https://github.com/hahnlab/CAFE5/files/5873227/tree3_ultrametric.txt)
[tree4_ultrametric.txt](https://github.com/hahnlab/CAFE5/files/5873229/tree4_ultrametric.txt)

Thank you for your help.

**Comment by benfulton** [comment]
That is just because you have an extra blank line at the end of the gene family file. I will try to add a better error message for that.

**Comment by pfb2201** [comment]
Hi! I am having the same problem, where it states "species was not found in gene family"
I tried the following solution
1. dos2unix
2. convert to csv

the column headers are definitely there, and the columns are filled out. 

My species names are all simple and without spaces (6 letter names).

**Comment by pfb2201** [comment]
My GeneCount file is "ASCII text" and my tree file is "ASCII text, with very long lines, with no line terminators." Could you help me figure out what else to check with the formatting?

**Comment by benfulton** [comment]
See Discussion #78 for some possible answers.
