### ISSUE TITLE
Installing CAFE5 with conda

### ISSUE THREAD

**Issue by ShuaiNIEgithub** [hahnlab/CAFE5#49]
There is no doubt that CAFE5 is a superb tool. It has made revolutionary improvements compared to the previous versions.
But I failed at this step of the installation, so I would like to ask when will it be possible to install quickly with conda? I can't wait to use it.

**Comment by benfulton** [comment]
I'm not sure that a Conda package would do anything differently than the current makefile. What error did you receive?

**Comment by ZicoHara** [comment]
Can conda install CAFE5? which channel please.
