### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by angelajmcd** [hahnlab/CAFE5#50]
Hi there,
 
I'm getting the below error message after make. I tried commenting out the atlas bits in the config.h file, but that didn't help. Any ideas?

Thanks,
Angela

`g++ -std=c++11 -I. -O3 -include config.h   -c src/base_model.cpp -o obj/base_model.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/cafexp.cpp -o obj/cafexp.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/clade.cpp -o obj/clade.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/core.cpp -o obj/core.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/error_model.cpp -o obj/error_model.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/execute.cpp -o obj/execute.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/gamma.cpp -o obj/gamma.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/gamma_core.cpp -o obj/gamma_core.o
src/gamma_core.cpp:96:86: warning: 'bind2nd<std::__1::divides<double>, double>' is deprecated [-Wdeprecated-declarations]
    transform(numerators.begin(), numerators.end(), posterior_probabilities.begin(), bind2nd(divides<double>(), denominator));
                                                                                     ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/functional:1079:1: note: 'bind2nd<std::__1::divides<double>, double>' has been explicitly marked deprecated here
_LIBCPP_DEPRECATED_IN_CXX11 inline _LIBCPP_INLINE_VISIBILITY
^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__config:1101:39: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
#  define _LIBCPP_DEPRECATED_IN_CXX11 _LIBCPP_DEPRECATED
                                      ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__config:1090:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
1 warning generated.
g++ -std=c++11 -I. -O3 -include config.h   -c src/gene_family.cpp -o obj/gene_family.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/gene_family_reconstructor.cpp -o obj/gene_family_reconstructor.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/io.cpp -o obj/io.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/lambda.cpp -o obj/lambda.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/matrix_cache.cpp -o obj/matrix_cache.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/optimizer.cpp -o obj/optimizer.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/optimizer_scorer.cpp -o obj/optimizer_scorer.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/poisson.cpp -o obj/poisson.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/probability.cpp -o obj/probability.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/root_distribution.cpp -o obj/root_distribution.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/root_equilibrium_distribution.cpp -o obj/root_equilibrium_distribution.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/simulator.cpp -o obj/simulator.o
g++ -std=c++11 -I. -O3 -include config.h   -c src/user_data.cpp -o obj/user_data.o
g++ -std=c++11 -I. -O3 -include config.h  -c main.cpp -o obj/main.o
g++ -std=c++11 -O3  -o bin/cafexp -I. obj/base_model.o obj/cafexp.o obj/clade.o obj/core.o obj/error_model.o obj/execute.o obj/gamma.o obj/gamma_core.o obj/gene_family.o obj/gene_family_reconstructor.o obj/io.o obj/lambda.o obj/matrix_cache.o obj/optimizer.o obj/optimizer_scorer.o obj/poisson.o obj/probability.o obj/root_distribution.o obj/root_equilibrium_distribution.o obj/simulator.o obj/user_data.o obj/main.o -lsatlas -lmkl_intel_lp64 -lm  
ld: library not found for -lsatlas
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/cafexp] Error 1
`

**Comment by benfulton** [comment]
There is a line in the Makefile that has "-lsatlas" in it. Removing that should get it to compile.

But how did you get linked with Atlas? If you don't have it on your system,

./configure
make clean
make

should fix it.

**Comment by angelajmcd** [comment]
Hi Ben,

I had tried to install Atlas, but to my knowledge it didn't work... 

Anyway, your instructions didn't work; I kept getting Atlas errors whichever way I tried. I successfully installed CAFE5 on a different computer for now.

Thanks,
Angela
