### ISSUE TITLE
Failed to initialize any reasonable values

### ISSUE THREAD

**Issue by marimaro** [hahnlab/CAFE5#53]
Hello,

I am trying to do an expansion/retraction analysis on a plant genome dataset. I have 10 different species (both monocots and eudicots with different ploidies) and I keep encountering this error (I have already removed a few families that had really high differences in species I was not so interested in).

I don't understand why this is happening, because if I am searching for expansions, this is exactly what I am looking for, right? Many genes in a family in a single species. 

Can you please help me in some way? I have used the script `clade_and_size_filter.py` to filter the dataset and tried different gamma categories values and the error persists.

Thank you in advance!

> 
> Families with largest size differentials:
> OG0000346: 27
> OG0000031: 26
> OG0000136: 26
> OG0000227: 25
> OG0000161: 25
> OG0000118: 25
> OG0000214: 25
> OG0000364: 25
> OG0000100: 25
> OG0000620: 24
> OG0000080: 24
> OG0000035: 24
> OG0000078: 24
> OG0000106: 23
> OG0001614: 23
> OG0000122: 23
> OG0001245: 23
> OG0000782: 23
> OG0000575: 23
> OG0000871: 23
> 
> You may want to try removing the top few families with the largest difference
> between the max and min counts and then re-run the analysis.
> 
> Failed to initialize any reasonable values
>

**Comment by sajjadasaf** [comment]
Hello,
I have got same problem. Anybody have solved  this issue?

**Comment by benfulton** [comment]
You may have better luck asking on the mailing list. https://groups.google.com/g/hahnlabcafe

**Comment by Rhia15** [comment]
Hi, has anyone solved this as I am also experiencing the same problem :) Thank you!
