### ISSUE TITLE
Species not found in gene family

### ISSUE THREAD

**Issue by arunsethuraman** [hahnlab/CAFE5#54]
Hi folks,
I'm trying to run CAFE5 on a dataset that I formatted based on the output of Orthofinder (attached - hymenoptera_orthogroups.txt), and the binary, rooted, ultrametric tree (attached - hymtree_ultrametric.txt). I keep ending up with a weird error upon running this command:
cafe5 -i hymenoptera_orthogroups.txt -t hymtree_ultrametric.txt
Command line: cafe5 -i hymenoptera_orthogroups.txt -t hymtree_ultrametric.txt
Tric was not found in gene family x

Any thoughts or advice would be greatly appreciated!
Thanks!
Arun
[hymenoptera_orthogroups.txt](https://github.com/hahnlab/CAFE5/files/6193102/hymenoptera_orthogroups.txt)
[hymtree_ultrametric.txt](https://github.com/hahnlab/CAFE5/files/6193110/hymtree_ultrametric.txt)

**Comment by benfulton** [comment]
This generally indicates that your file has Windows-style line endings. You can use the Linux program dos2unix to fix the line endings.

**Comment by arunsethuraman** [comment]
Goodness - such a rookie error on my part! Thank you! This fixed the issue instantly.

**Comment by souzaems** [comment]
Hi
I have the same issue, but the dos2unix doesn't work and the same message appear to me.

=(

**Comment by souzaems** [comment]
I changed the gene files for .csv and works

**Comment by kat-king** [comment]
Hi, I'm having this same issue but the two solutions above don't work for me. Any suggestions?

**Comment by benfulton** [comment]
Can you share your tree and family files?
