### ISSUE TITLE
make  error 

### ISSUE THREAD

**Issue by yybgood** [hahnlab/CAFE5#55]
when i install cafe ,i got that error
`icc -std=c++11 -O3 -fopenmp -o bin/cafexp -I. obj/user_data.o obj/simulator.o obj/optimizer.o obj/cafexp.o obj/probability.o obj/gene_family.o obj/gamma.o obj/matrix_cache.o obj/base_model.o obj/error_model.o obj/io.o obj/core.o obj/lambda.o obj/root_equilibrium_distribution.o obj/gamma_core.o obj/clade.o obj/optimizer_scorer.o obj/poisson.o obj/root_distribution.o obj/execute.o obj/gene_family_reconstructor.o obj/main.o -lmkl_sequential -lmkl_core -lmkl_intel_lp64 -lm
obj/clade.o: In function `parse_newick(std::string, bool)':
clade.cpp:(.text+0x7c5): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::basic_regex<char, std::regex_traits<char> > const&, std::bitset<11ul>)'
clade.cpp:(.text+0x7d2): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator()'
clade.cpp:(.text+0x800): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator!=(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
clade.cpp:(.text+0x81a): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
clade.cpp:(.text+0x939): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
clade.cpp:(.text+0xa3d): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
clade.cpp:(.text+0xafc): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
clade.cpp:(.text+0xbb6): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
obj/clade.o:clade.cpp:(.text+0xc6c): more undefined references to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()' follow
obj/clade.o: In function `parse_newick(std::string, bool)':
clade.cpp:(.text+0xd24): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator++(int)'
clade.cpp:(.text+0xd46): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator!=(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
clade.cpp:(.text+0x10da): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
clade.cpp:(.text+0x11cb): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
make: *** [bin/cafexp] Error 1`
**The gcc version is **
`$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)`
I don't have the root right

**Comment by benfulton** [comment]
You need at least gcc 4.9.

**Comment by yybgood** [comment]
thanks

**Comment by NINGCHINA** [comment]
(base) ➜  CAFE5 make
g++ -std=c++11 -O3  -o bin/cafe5 -I. obj/base_model.o obj/cafexp.o obj/clade.o obj/core.o obj/easylogging++.o obj/error_model.o obj/execute.o obj/gamma.o obj/gamma_core.o obj/gene_family.o obj/gene_family_reconstructor.o obj/io.o obj/lambda.o obj/likelihood_ratio.o obj/matrix_cache.o obj/optimizer.o obj/optimizer_scorer.o obj/poisson.o obj/probability.o obj/root_equilibrium_distribution.o obj/simulator.o obj/user_data.o obj/main.o -lm
Undefined symbols for architecture x86_64:
  "_omp_set_num_threads", referenced from:
      cafe5(int, char* const*) in cafexp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/cafe5] Error 1
