### ISSUE TITLE
Nelder-Mead optimization algorithm

### ISSUE THREAD

**Issue by shelbyLanda** [hahnlab/CAFE5#57]
Hello,

I am finding that orthogroups I am interested in are being removed at optimization. Is there a way to disable the optimizer?

Thank you,
Shelby Landa

**Comment by benfulton** [comment]
Nelder-Mead is the process used to determine the most likely lambda. You probably want --zero_root to disable the removal of families which are likely to have a zero count at the root. If you really want to disable Nelder-Mead, use -l to specify the lambda you want to use instead,

**Comment by shelbyLanda** [comment]
Using the --zero_root flag produced the desired results. Thank you for the reply.
