### ISSUE TITLE
CAFE5 hangs with no output

### ISSUE THREAD

**Issue by katieemelianova** [hahnlab/CAFE5#58]
I am trying to run CAFE5 on my tree and gene families, but when I run CAFE it begins a run with the following and then hangs; I ran it overnight and the results directory is empty and the stdout has not changed from the initial output. I have tried running the exact same command using the test data provided and this works fine and is finished in minute or so.

What output says when I run my data:

```
Command line: /home/kemelianova/software/CAFE5/bin/cafe5 -i Orthogroups.GeneCount.renamed.tsv -t allseqs.partitions.txt.newick 

Filtering families not present at the root from: 24794 to 13353

No root family size distribution specified, using uniform distribution

Optimizer strategy: Nelder-Mead with similarity cutoff
Iterations: 300
Expansion: 2
Reflection: 1

Starting Search for Initial Parameter Values
Lambda:  1.246526834209
```

The top of my gene families files looks like this:
```
Desc	Family ID	Bconchifolia	Csativus	Fvesca	Gmax	Mdomestica	Ppersica	Hsandwicensis	Total
(null)	OG0000000	0	0	0	0	0	0	2590	2590
(null)	OG0000001	0	0	0	2	0	0	347	349
(null)	OG0000002	0	0	0	239	1	0	0	240
(null)	OG0000003	0	0	1	0	0	0	223	224
(null)	OG0000004	0	7	97	0	3	0	85	192
(null)	OG0000005	43	11	17	17	66	31	5	190
(null)	OG0000006	53	12	37	5	21	27	13	168
(null)	OG0000007	0	0	0	0	0	0	157	157
(null)	OG0000008	12	5	24	33	43	28	4	149
```

and my newick file looks like this:
```
(((Bconchifolia:0.1135623761,Hsandwicensis:0.0696081000):0.0971567222,Csativus:0.1639220766):0.0395326117,(Fvesca:0.1018609856,(Mdomestica:0.0631677766,Ppersica:0.0450850164):0.0261263160):0.0615693063,Gmax:0.2068897414);
```

I have since realised I had the "Total" column still in the gene families file, but removing it doesn't change any of the above behaviour.

Is there anything I'm doing wrong or can find out what's happening to make it hang for so long?

**Comment by katieemelianova** [comment]
Whoops - fixed it by remove lines where any taxon has a zero in it. Sorry! :)

**Comment by WenChangYu** [comment]
Hi [katieemelianova](https://github.com/katieemelianova),

I meet the same error. My tree file and gene family file look the same as yours.
You said "remove lines where any taxon has a zero" can fix the error.
But after I removed the lines, the same error also came out.
Waht's more, the example file https://github.com/hahnlab/CAFE5/blob/master/examples/mammal_gene_families.txt contains the lines where any taxon has a zero in it. So I am a little confused.

Could you give me some suggestions?
Thanks in advance.

Chunyang

**Comment by WenChangYu** [comment]
> Simply having a count of 0 in your family sizes shouldn't cause any errors: this is perfectly allowed. However, in the example above, many families wouldn't exist in the root (they seem to only exist in one species). This might cause problems, especially given the large sizes in the single species that do have them.
> 
> Matt

Thanks for your kindly reply. 
I deleted the families that contain large range of counts, then it works.

Chunyang

**Comment by xiongqian123456789** [comment]
I have been modified the data by the ways as above:
1. delete the OGs only in one species;
2. delete the OGs lines where any taxon has a zero,
And also met the  same error with no output.
The attached file is the original input file.
Really appreciated for your help!
