### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by Axolotl233** [hahnlab/CAFE5#60]
Hi community, 

I encounted a error when I intall cafe5
the stderr is:

```
g++ -std=c++11 -O3 -fopenmp -o bin/cafe5 -I. obj/simulator.o obj/optimizer.o obj/likelihood_ratio.o obj/cafexp.o obj/gene_family_reconstructor.o obj/gene_family.o obj/gamma.o obj/gamma_core.o obj/base_model.o obj/user_data.o obj/error_model.o obj/matrix_cache.o obj/core.o obj/lambda.o obj/io.o obj/root_equilibrium_distribution.o obj/clade.o obj/optimizer_scorer.o obj/poisson.o obj/execute.o obj/probability.o obj/easylogging++.o obj/main.o -lopenblas -lopenblas -lm  
obj/matrix_cache.o: In function `matrix::multiply(std::vector<double, std::allocator<double> > const&, int, int, int, int, double*) const':
matrix_cache.cpp:(.text+0x31f): undefined reference to `cblas_dgemm(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, double, double const*, int, double const*, int, double, double*, int)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:32: bin/cafe5] Error 1
```

my gcc version is :
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC)
```

i can't solve this problem by my self, if you can help me, i will be very appreciated

**Comment by benfulton** [comment]
Your link line is requesting OpenBlas for the math library, but not finding it. 

Before running the make, run

export LDPATH=/path/to/openblas:$LDPATH

If you don't know the appropriate path to OpenBlas on your system, ask your administrator.

**Comment by Axolotl233** [comment]
Hi Ben,
thank you for your rapidly reply, I installed `OpenBLAS-0.3.17` with directory constructure which upload in appendix. It was compiled in `build` folder.

i tyr to add the path of folder `OpenBLAS-0.3.17` to variable `LDPATH`, `LD_LIBRARY_PATH`, `C_INCLUDE_PATH`, `CPLUS_INCLUDE_PATH`, but Error is still exist, could you have any advice for this ?

my command are here
```
export LD_LIBRARY_PATH=$HOME/software/OpenBLAS-0.3.17:$LD_LIBRARY_PATH
export C_INCLUDE_PATH="$C_INCLUDE_PATH:$HOME/software/OpenBLAS-0.3.17"
export CPLUS_INCLUDE_PATH="CPLUS_INCLUDE_PATH:$HOME/software/OpenBLAS-0.3.17"
```
![OpenBlas](https://user-images.githubusercontent.com/45548556/131605544-c69a58db-78a7-4643-a487-5dd1dd6eece2.png)

**Comment by Axolotl233** [comment]
is there any update? the problem still exists

**Comment by benfulton** [comment]
Your export commands are probably not quite right. There should be a "lib" and "include" directories under the OpenBLAS root directory; change the paths to reflect those subdirectories rather than the root OpenBLAS directory.

**Comment by Axolotl233** [comment]
Hi,
I think i have installed OpenBLAS properly, but there still have complie error, could you have any advices for this?
![openblas](https://user-images.githubusercontent.com/45548556/134465388-89f85d72-3e17-47e5-b60c-414024bdd28a.jpg)

**Comment by benfulton** [comment]
Yes, you can see the lib and include directories there.

**Comment by Axolotl233** [comment]
but compile error not be fixed... hmmm STDERR is same as before
is there something wrong？

**Comment by Axolotl233** [comment]
ok, i run`make clean` and recomplie it with `make` command, it works well. the problem is fixed
thank you, Ben
