### ISSUE TITLE
The tree required for a multiple lambda run

### ISSUE THREAD

**Issue by ndrubins** [hahnlab/CAFE5#61]
Hi,

I apologize if this is a trivial question. In the example you provide for running cafe5 for estimating multiple lambdas you label the clades in the tree for which you want the separate lambdas estimated. It seems you've replaced the branch lengths with the lambda labels because in the single lambda estimation tree example I see the branch lengths. What am I missing?

Thanks

**Comment by ndrubins** [comment]
Actually I think I missed that the lambda labeled tree is a separate tree file, with the same topology and tip labels but instead of branch lengths it has the lambda group labels.

Sorry and thanks

**Comment by benfulton** [comment]
Glad you figured out the issue!
