### ISSUE TITLE
Family p-values - digits

### ISSUE THREAD

**Issue by tgstoecker** [hahnlab/CAFE5#62]
Hi everyone,
short question - where in the code is it specified how many digits after the decimal point are reported?
Currently, any value below 0.001 gets turned into a 0.

I tried finding it in the src files but wasn't successful thus far.
A quick pointer would be much appreciated - so I can fiddle around with that part specifically.
Thx!

**Comment by benfulton** [comment]
It's printed in a few places, I think. In gene_family_reconstructor.cpp you'll see it on line 226. It's just printed with an ostream so you would probably want to change the stream's precision.

**Comment by tgstoecker** [comment]
Thx, that helped a lot!
