### ISSUE TITLE
ID of the tree's internal nodes

### ISSUE THREAD

**Issue by laruzzante** [hahnlab/CAFE5#63]
Hi, I use the Base_change.tab result file for further processing with R to get expansion/contraction counts at each internal node level.
However the naming of the internal nodes (appearing in the header of the Base_change.tab file) does not correspond to any naming scheme I could find across phylogeny R packages (ape, reading from either Newick of Nexus file formats).
Where can I find a look-up table for this? Because as of now I cannot use CAFE's internal node labeling system, hence no use for the Base_change.tab file, if not only for the leaves.
Thank you,
Livio

**Comment by benfulton** [comment]
What naming scheme do the R packages use?

**Comment by laruzzante** [comment]
> What naming scheme do the R packages use?

Hi Ben, I could not find out what the scheme is, I spent a bit of time trying to figure it out, no results.
I did finally write a script to parse the file with regular expressions in python for every OG tree line in the 'Base_asr.tre' file and that is working fine currently. That was a complicated script to write though. Id be happy to know if in the future the naming scheme currently used by CAFE will match 'ape' for example (internal node numbering etc).

Here I attached a screenshot of a simple tree manipulation with 'ape', to show the labels. I used a part of a tree printed on the 'Base_asr.tre' file, only removed the tree name at the beginning of the string. Ape seems to use the annotated part of the node as node label, understandably, but then seems to provide a table with the actual ID numbers that they use to map the object.
See: 'tree$edge'. I have not been able to decipher the criteria they use.

Here the script for reproducibility:

`library(ape)

tree <- read.tree(text='((Parasteatoda_tepidariorum<285>_1:138.531,Stegodyphus_mimosarum<284>_1:138.531)<297>_1:187.093,Centruroides_sculpturatus<296>_3:325.625)<313>_1:46.2175;')

plot(tree, show.tip.label = TRUE, show.node.label = TRUE)

tree$tip.label
tree$node.label
tree$edge`

![image](https://user-images.githubusercontent.com/38459199/150311954-109873eb-65bb-48b0-a479-54659e7be716.png)

**Comment by laruzzante** [comment]
From ape's manual:

edge
a two-column matrix of mode numeric where each row represents an edge of the tree; the nodes and the tips are symbolized with numbers; the tips are numbered 1, 2, …, and the nodes are numbered after the tips. For each row, the first column gives the ancestor.

**Comment by benfulton** [comment]
I've added a gist that reverse engineers the Ape tree loader so I can understand the numbering scheme. Haven't managed it yet though.

https://gist.github.com/benfulton/dbb1be9edd3a023093fb5a6cee3a03af

**Comment by dariober** [comment]
I'm having the same problem. If at all possible, it would be useful if cafe preserved the node names in the input tree for all output it produces. Node names, if not already there, can be set in R using e.g.:

```
library(ape)
tree <- read.tree('my.tree')
tree$node.label <- paste0("node", seq(1:tree$Nnode)) # To make node names as: node1, node2, etc
write.tree(tree, 'my2.tree')
```

Cafe's output would be, e.g.:

```
#Taxon_ID         | Increase | Decrease
node10            |        9 |      168
node13            |        0 |       17
etc
```

instead of:

```
#Taxon_ID                   | Increase | Decrease
<82>                        |        9 |      168
<66>                        |        0 |       17
etc
```

I think this would be preferable over making assumptions about the naming scheme of ape since that could change and there is no standard for naming nodes, different packages could name things differently.

**Comment by benfulton** [comment]
That seems reasonable. I'll look into it for the next release.
