### ISSUE TITLE
Filtering families not present at the root

### ISSUE THREAD

**Issue by francicco** [hahnlab/CAFE5#66]
Hi,

because multiple gene families are discarded from my dataset, I was wondering what is the rational behind "Filtering families not present at the root from". Is there any way I can get around it?

Cheers
Francesco

**Comment by benfulton** [comment]
Answered on the mailing list.

**Comment by camille-puginier** [comment]
Hello ! 
I had basically the same question. 
Is there somewhere I can find the explanation on how the gene families are discarded ?
Thank you in advance
Camille

**Comment by benfulton** [comment]
https://groups.google.com/g/hahnlabcafe/c/xSYiBLBaqA0

**Comment by camille-puginier** [comment]
Thank you for your help !
