### ISSUE TITLE
Families with largest size differentials for fungi

### ISSUE THREAD

**Issue by xiaoaozqd** [hahnlab/CAFE5#68]
Sorry I  can't sign in https://groups.google.com/
**Describe the bug**
Families with largest size differentials: fungi
**To Reproduce**
1. python2 clade_and_size_filter.py -s -i cafe.data -o filtered_cafe_input2.txt
2. cp filtered_cafe_input2.txt filtered_cafe_input5.txt
3. delete the Families with largest size differentials output by cafe5 (about 9255 OG to 4700 OG)
4. cafe5 -i filtered_cafe_input5.txt -t r8s_ultrametric5.txt -p -k 2 -o k2p
5. No OG output

**Expected behavior**
run successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/10625828/150341177-125832a7-a136-46b9-bc51-9a3f4f17fb9a.png)

Families with largest size differentials:

You may want to try removing the top few families with the largest difference
between the max and min counts and then re-run the analysis.
.

**Desktop (please complete the following information):**
 - OS: [e.g. Linux 3.10.0-957.21.3.el7.x86_64 #]

**Additional context**
[r8s_ultrametric5.txt](https://github.com/hahnlab/CAFE5/files/7905216/r8s_ultrametric5.txt)
[filtered_cafe_input5.txt](https://github.com/hahnlab/CAFE5/files/7905218/filtered_cafe_input5.txt)

**Comment by caord-1** [comment]
Hello, I also encountered this problem. I want to know how you have solved it. please!
