### ISSUE TITLE
visualization for cafe5 output

### ISSUE THREAD

**Issue by ShadoWyyyy** [hahnlab/CAFE5#69]
I just use CAFE5 to do the analysis of my dataset, and I am wondering how I am going to visualize it, I don't know how to draw a tree which show gene family expansion and contraction on its branch, I look for ideas on website, it appears that all the python scripts and cafe_fig are fit for old version of CAFE, so I am thinking about it, maybe it is easy to do, but I am kind of fresh, so any help would also be ok

**Comment by xbx-xbx-1208** [comment]
I have the same question...

**Comment by jaredbernard** [comment]
@ShadoWyyyy, I think you're right; the input for cafe_fig is supposed to be a `.cafe` file type, and CAFE5 seems to have done away with this. @benfulton, do you know what output has replaced the `.cafe` files?

**Comment by benfulton** [comment]
CAFE5 outputs a variety of text and tab-delimited files. What sort of visualization would you like to see?

**Comment by jaredbernard** [comment]
I think we are all interested something similar to what Kremer shows in [CAFE_fig](https://github.com/LKremer/CAFE_fig), but it requires the `.cafe` file type.

**Comment by benfulton** [comment]
I've never seen that before. Let me take a look at it.

**Comment by jaredbernard** [comment]
Some have used it for this purpose, for example [Hazzouri et al. 2020](https://doi.org/10.1038/s42003-020-1060-8).

**Comment by NayeliGutierrez** [comment]
Hi all, is there any update on this?

**Comment by benfulton** [comment]
We are planning to release an updated version that supports CAFE_fig. I can't give you any timeline on it yet though.

**Comment by NayeliGutierrez** [comment]
This is great news, thanks!

**Comment by jaredbernard** [comment]
Related to this topic, I noticed that in the tutorial.md under "Summarizing the Output" it says "If you open file results/base_clade_results.txt, you will see, for each branch, how many families underwent expansions, contractions, and how many are rapidly evolving. In fact, we provide yet another script that allows you to plot these numbers on a phylogenetic tree." But the script provided is a python script which seems to be from a prior version of Cafe. Is there a replacement?

**Comment by melissarincons** [comment]
Hi,
I have the same question.
I'm interested in plotting a summary tree that shows families' average expansion/contraction across my phylogeny.
I hope CAFE5.1 will be ready soon.

**Comment by fernanmelendez** [comment]
Hello,

I have a similar inquiry. I want to create a condensed tree that displays the average expansion/contraction of families throughout my phylogenetic tree. I'm looking forward to the update! Thank you for your time.

**Comment by moshi4** [comment]
Hi,

I developed [CafePlotter](https://github.com/moshi4/CafePlotter), a tool for plotting CAFE5 gene family expansion/contraction result.
It is a simple visualization tool, but I think it can be used to quickly check the overall results.

CafePlotter outputs the following figure.

![summary_all_gene_family](https://user-images.githubusercontent.com/41852815/222719145-c83ce4a0-5dd7-487b-b710-ab4e34fe76ad.png)

![2_gene_family](https://user-images.githubusercontent.com/41852815/222719162-732bc4ff-3722-4480-aea0-e694f8805004.png)

If you are interested, take a look at https://github.com/moshi4/CafePlotter.

**Comment by benfulton** [comment]
Hi Folks,

The repository has been updated with code that will write a report file in the CAFE4 style, which should allow CAFE_fig to generate a visualization again. There is also a script in the tutorial directory that will draw a simple tree.

My plan is to build a beta release this week, and a full CAFE 5.1 release soon afterwards. Please let me know if you see any immediate problems.

**Comment by iaunicorn** [comment]
Hi,

Thanks a lot for the update. When I just use cafe5_draw_tree.py, it always reported: FileNoFoundError: [Errno 2] No such file or directory:  './results/Base_report.cafe'. 
I am wondering if "results/Base_report.cafe" is also an output, right? How to solve this problem?

**Comment by benfulton** [comment]
You would have to download the current source code and compile it. The upcoming version will create that file in the output directory.

**Comment by iaunicorn** [comment]
Thanks. It worked:)

**Comment by mundoctor** [comment]
> Hi Folks,
> 
> The repository has been updated with code that will write a report file in the CAFE4 style, which should allow CAFE_fig to generate a visualization again. There is also a script in the tutorial directory that will draw a simple tree.
> 
> My plan is to build a beta release this week, and a full CAFE 5.1 release soon afterwards. Please let me know if you see any immediate problems.

Thank you, benfulton, it provides a great help, thank you for your contribution!

**Comment by Xacfran** [comment]
> Hi Folks,
> 
> The repository has been updated with code that will write a report file in the CAFE4 style, which should allow CAFE_fig to generate a visualization again. There is also a script in the tutorial directory that will draw a simple tree.
> 
> My plan is to build a beta release this week, and a full CAFE 5.1 release soon afterwards. Please let me know if you see any immediate problems.

Thanks for this! I extremely appreciate it. Something I noticed is that the cafe report is differently formatted when compared to the one given by CAFE_fig as an example, precisely the Viterby-P-values column in the CAFE_fig report. I am asking because there are gene families with significant expansions and contractions in my own data that are not being reported by CAFE_FIG, but they are indeed reported by CAFE plotter, which was previously mentioned by @moshi4 and to whom I also extend my appreciation. Also, do you think the gene loss/gain rates are accurately calculated by CAFE_fig to be submitted for publication?

**Comment by YuzhouGong** [comment]
Hi Guys,
I found that the .cafe file genereted by CAFE5 is different from the .cafe file generated by CAFE4 (4.2.1), like @Xacfran has mentioned, the Viterby-P-values column in CAFE4' result is not presented by CAFE5, which might casue wrong outputs of CAFE_fig (all nodes show +0/-0 expanded and contracted gene family).
CAFE_plotter developed by @moshi4 could visualize the outputs of CAFE5, it's a great visualization tool! But for my instance, there were too many expanded or contracted gene families on my tree nodes (like average 5 thousand), so I only interested in presenting the number of significantly expanded/contracted ones. CAFE_fig could only show significantly expanded/contracted gene families by droping the parameter --count_all_expansions, whereas no such function is added in CAFE_plotter (the tree drawn by CAFE_plotter shows all expanded/contracted gene families).
Is there any way to draw a tree only with significant expanded and contracted gene families numbers on branches and nodes using the outputs of CAFE5? I mean the way that we do not have to manually caculate the numbers of significant expanded/contracted gene families from files generated by CAFE5 (such as Base/Gamma_change.tab, Base/Gamma_family_results.txt, etc.).
Any suggestion will be welcomed!

**Comment by huangxiaoyun1123** [comment]
> Hi Guys, I found that the .cafe file genereted by CAFE5 is different from the .cafe file generated by CAFE4 (4.2.1), like @Xacfran has mentioned, the Viterby-P-values column in CAFE4' result is not presented by CAFE5, which might casue wrong outputs of CAFE_fig (all nodes show +0/-0 expanded and contracted gene family). CAFE_plotter developed by @moshi4 could visualize the outputs of CAFE5, it's a great visualization tool! But for my instance, there were too many expanded or contracted gene families on my tree nodes (like average 5 thousand), so I only interested in presenting the number of significantly expanded/contracted ones. CAFE_fig could only show significantly expanded/contracted gene families by droping the parameter --count_all_expansions, whereas no such function is added in CAFE_plotter (the tree drawn by CAFE_plotter shows all expanded/contracted gene families). Is there any way to draw a tree only with significant expanded and contracted gene families numbers on branches and nodes using the outputs of CAFE5? I mean the way that we do not have to manually caculate the numbers of significant expanded/contracted gene families from files generated by CAFE5 (such as Base/Gamma_change.tab, Base/Gamma_family_results.txt, etc.). Any suggestion will be welcomed!

I have the same problem as you, can you solve it, how to plot a graph that expands and shrinks significantly

**Comment by Fantacooke2** [comment]
Dear all ,  

I hope you are doing well.  

I am working with CAFE5 and analyzing the results from the following command:  

cafe5 -i ./filtered.cafe.input.txt -t ./tree.nwk -p -y ./lambda_tree.nwk -o multiplelambda


This produced several output files, including `Base_asr.tre`, `Base_change.tab`, and `Base_results.txt`, among others. I would like to visualize gene family expansion and contraction on each evolutionary branch, with numbers indicating the expansions, contractions, and significantly (p-value ≤ 0.01) evolving gene families.  

I tried CAFEPLOTTER but as mentionned previously by @YuzhouGong, there is a limitation.
Could you please provide guidance on the best approach to generate a plot showing gene families (Expansions/Contractions/Rapidly evolving families), iedally in three different colors? Specifically, which files should be used, and are there any recommended tools or scripts for this purpose?  

Thank you in advance for your help.  

Best regards
