### ISSUE TITLE
How to determine to use base or gamma model?

### ISSUE THREAD

**Issue by dzaccook** [hahnlab/CAFE5#79]
Hi, I can compare the model between single lambda and muti-lambda using CAFE4, but how can I compare the model between base and gamma model? Can I use the AIC criterion basing on the likelihood? Thank you!

**Comment by hahnlab-user** [comment]
Sorry, but I don't believe this type of comparison is a fair one, as these are two very different models. You just have to decide externally which one you would like to use.

**Comment by dzaccook** [comment]
Than you!
