### ISSUE TITLE
std::bad_alloc error

### ISSUE THREAD

**Issue by ryan-preble** [hahnlab/CAFE5#86]
Running CAFE5 on large orthogroups with a specified lambda always results in failure. Error log reports:
`Command line: /home/rsp98/programs/CAFE5/bin/cafe5 -t SpeciesTree_Rooted_node_labels.ultrametric.txt -i large_Orthogroups.GeneCount.filtered.tsv -l 0.4811101920665 -o large_results -eBase_error_model.txt -c 40

Filtering families not present at the root from: 57 to 16

No root family size distribution specified, using uniform distribution
Inferring processes for Base model
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc`

This bad memory allocation occurs regardless of the system the analysis is run and regardless of the number of cores used. I ran this analysis using 8 species, 6 of which form a closely related clade and two of which are very distantly related to that clade.

**Comment by benfulton** [comment]
bad_alloc indicates that the system is out of memory. How large are the large orthogroups, and how much memory does the system have?

**Comment by ryan-preble** [comment]
> bad_alloc indicates that the system is out of memory. How large are the large orthogroups, and how much memory does the system have?

The largest orthogroups have up to 1300 genes across all species, followed closely by 800 and 500 genes. I tried to run the analysis on two systems: my local machine (16 gb ram, 12 cores) and on one of my analysis servers (1 tb ram, 80 cores). Unless I underestimate the memory complexity of CAFE5, this leads me to believe there was a bad variable instantiation somewhere

**Comment by benfulton** [comment]
Can you share the files you're running with? (Send them direct to me if you would rather not share them publicly)

**Comment by ryan-preble** [comment]
[Base_error_model.txt](https://github.com/hahnlab/CAFE5/files/9803488/Base_error_model.txt)
[large_Orthogroups.GeneCount.filtered.tsv.txt](https://github.com/hahnlab/CAFE5/files/9803489/large_Orthogroups.GeneCount.filtered.tsv.txt)
[Orthogroups.GeneCount.filtered.tsv.txt](https://github.com/hahnlab/CAFE5/files/9803490/Orthogroups.GeneCount.filtered.tsv.txt)
[SpeciesTree_Rooted_node_labels.ultrametric.txt](https://github.com/hahnlab/CAFE5/files/9803491/SpeciesTree_Rooted_node_labels.ultrametric.txt)

**Comment by benfulton** [comment]
The first line of the error model says that you expect no more that 170 maximum families - change that to a little more than your max family size and you should be able to get past the error. (This is an oddity of the CAFE interface and we'll try to get it fixed in the next version.) Your tree does appear to have some whole genome duplication events in it; these may end up confusing the reconstruction, though.

**Comment by ryan-preble** [comment]
Ok, thank you! Shall I close the issue or leave it open?

**Comment by benfulton** [comment]
Go ahead and close it; we'll start a new one for the interface changes.
