### ISSUE TITLE
How to specify multiple fossil time points when preparing an r8s run file？

### ISSUE THREAD

**Issue by sunjiahe-hub** [hahnlab/CAFE5#87]
Hi, I have a question about the script provided by cafe5 to prepare r8s to run
 ($ python prep_r8s.py -i maximum_likelihood_tree.txt -o r8s_ctl_file.txt -s 35157236 -p 'human,cat' -c '94') .

 it is observed that only one fossil node is specified in the command. 

Can I specify the time of multiple fossil nodes through this script? How should I specify this?

Looking forward to your reply

**Comment by hahnlab-user** [comment]
Sorry, but you'd have to ask the developers of r8s.

**Comment by sunjiahe-hub** [comment]
Thank you for your reply！
ok！
