### ISSUE TITLE
cafexp.cpp:(.text+0xe98): undefined reference to `omp_set_num_threads'

### ISSUE THREAD

**Issue by RuiqiaoHe** [hahnlab/CAFE5#94]
I tried to install CAFE5 in my linux system. However, after `make`, it encountered error as follows:
```
obj/cafexp.o: In function `cafe5(int, char* const*)':
cafexp.cpp:(.text+0xe98): undefined reference to `omp_set_num_threads'
```
My gcc version is 6.3.0 in linux. Could you please help me with this error?

**Comment by benfulton** [comment]
Can you post the full output that you get?

**Comment by RuiqiaoHe** [comment]
I used version is https://github.com/hahnlab/CAFE5/releases/download/v5.0/CAFE5-5.0.0.tar.gz. After moving into the CAFE5 folder, I typed `$ ./configure` and then `$ make`, it returned error:
```
g++ -std=c++11 -O3  -o bin/cafe5 -I. obj/base_model.o obj/cafexp.o obj/clade.o obj/core.o obj/easylogging++.o obj/error_model.o obj/execute.o obj/gamma_core.o obj/gamma.o obj/gene_family.o obj/gene_family_reconstructor.o obj/io.o obj/lambda.o obj/likelihood_ratio.o obj/matrix_cache.o obj/optimizer.o obj/optimizer_scorer.o obj/poisson.o obj/probability.o obj/root_equilibrium_distribution.o obj/simulator.o obj/user_data.o obj/main.o -lm  
obj/cafexp.o: In function `cafe5(int, char* const*)':
cafexp.cpp:(.text+0xe98): undefined reference to `omp_set_num_threads'
make: *** [bin/cafe5] Error 1
```
Thank you for your kindly help!

**Comment by benfulton** [comment]
If you look in the Makefile there should be a line like

`LINKER = $(LD) -std=c++11 -O3 -o`

Modify that to 

`LINKER = $(LD) -std=c++11 -fopen -O3 -o `

And it should work.
